name: Building the Java project
on: [workflow_dispatch]
jobs: 
    build-java: 
          runs-on: ubuntu-latest
          steps:
             - name: Checkout Repo
               uses: actions/checkout@v3            
             - name: Setup JDK 
               uses: actions/setup-java@v3
               with:
                   distribution: 'temurin'
                   java-version: '11'
             - name: Build with Maven
               run: mvn clean install 
           
             - name: Compiling with Maven
               run: mvn compile
         
             - name: Packing into jar
               run: mvn package 
             - run: ls -l
               
             - run: echo "Build Succesfully..."
   
    DockerbuildJob:
              name: Building the Dockerfile
              needs: build-java
              runs-on: ubuntu-latest
              steps:
                - uses: actions/checkout@v3
        
                - name: Login into Dockerhub1
                  env:
                   DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
                   DOCKER_PASS: ${{secrets.DOCKERHUB_TOKEN }}
                  run: | 
                     docker login -u $DOCKER_USER -p $DOCKER_PASS 
               
                # - name: Download Artifact
                #   uses: action/download-artifact@v2
                #   with:
                #      name: final-build
                #      path: artifacts/
                #      run: echo "----Downloaded succesfully-----"
                - name: Build the Docker image
                  run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/sampledocker:latest  -f  Dockerfile . 
                 # working-directory: artifacts
          
                - name: Push the Docker Image
                  run: docker push ${{secrets.DOCKERHUB_USERNAME}}/sampledocker:latest